<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2f615e62ff1d2873c91353c04d890561
{
    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'Svg\\' => 4,
            'Sabberworm\\CSS\\' => 15,
        ),
        'F' =>
        array (
            'FontLib\\' => 8,
        ),
        'D' =>
        array (
            'Dompdf\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Svg\\' =>
        array (
            0 => __DIR__ . '/..' . '/phenx/php-svg-lib/src/Svg',
        ),
        'Sabberworm\\CSS\\' =>
        array (
            0 => __DIR__ . '/..' . '/sabberworm/php-css-parser/src',
        ),
        'FontLib\\' =>
        array (
            0 => __DIR__ . '/..' . '/phenx/php-font-lib/src/FontLib',
        ),
        'Dompdf\\' =>
        array (
            0 => __DIR__ . '/..' . '/dompdf/dompdf/src',
        ),
    );

    public static $classMap = array (
        'BaseDatos' => __DIR__ . '/../..' . '/app/config/Database.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Controlador' => __DIR__ . '/../..' . '/app/libs/Controlador.php',
        'ControladorAdmin' => __DIR__ . '/../..' . '/app/controladores/ControladorAdmin.php',
        'ControladorAutenticacion' => __DIR__ . '/../..' . '/app/controladores/ControladorAutenticacion.php',
        'ControladorCliente' => __DIR__ . '/../..' . '/app/controladores/ControladorCliente.php',
        'ControladorEmpleado' => __DIR__ . '/../..' . '/app/controladores/ControladorEmpleado.php',
        'ControladorInicio' => __DIR__ . '/../..' . '/app/controladores/ControladorInicio.php',
        'ControladorReportes' => __DIR__ . '/../..' . '/app/controladores/ControladorReportes.php',
        'Dompdf\\Cpdf' => __DIR__ . '/..' . '/dompdf/dompdf/lib/Cpdf.php',
        'HTML5_Data' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/Data.php',
        'HTML5_InputStream' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/InputStream.php',
        'HTML5_Parser' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/Parser.php',
        'HTML5_Tokenizer' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/Tokenizer.php',
        'HTML5_TreeBuilder' => __DIR__ . '/..' . '/dompdf/dompdf/lib/html5lib/TreeBuilder.php',
        'Modelo' => __DIR__ . '/../..' . '/app/libs/Modelo.php',
        'ModeloAsignacion' => __DIR__ . '/../..' . '/app/modelos/ModeloAsignacion.php',
        'ModeloAvance' => __DIR__ . '/../..' . '/app/modelos/ModeloAvance.php',
        'ModeloCliente' => __DIR__ . '/../..' . '/app/modelos/ModeloCliente.php',
        'ModeloEmpleado' => __DIR__ . '/../..' . '/app/modelos/ModeloEmpleado.php',
        'ModeloProyecto' => __DIR__ . '/../..' . '/app/modelos/ModeloProyecto.php',
        'ModeloSolicitud' => __DIR__ . '/../..' . '/app/modelos/ModeloSolicitud.php',
        'ModeloUsuario' => __DIR__ . '/../..' . '/app/modelos/ModeloUsuario.php',
        'Seguridad' => __DIR__ . '/../..' . '/app/helpers/Seguridad.php',
        'Sesion' => __DIR__ . '/../..' . '/app/helpers/Sesion.php',
        'Validador' => __DIR__ . '/../..' . '/app/helpers/Validador.php',
        'Vista' => __DIR__ . '/../..' . '/app/libs/Vista.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2f615e62ff1d2873c91353c04d890561::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2f615e62ff1d2873c91353c04d890561::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2f615e62ff1d2873c91353c04d890561::$classMap;

        }, null, ClassLoader::class);
    }
}
