<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'BaseDatos' => $baseDir . '/app/config/Database.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Controlador' => $baseDir . '/app/libs/Controlador.php',
    'ControladorAdmin' => $baseDir . '/app/controladores/ControladorAdmin.php',
    'ControladorAutenticacion' => $baseDir . '/app/controladores/ControladorAutenticacion.php',
    'ControladorCliente' => $baseDir . '/app/controladores/ControladorCliente.php',
    'ControladorEmpleado' => $baseDir . '/app/controladores/ControladorEmpleado.php',
    'ControladorInicio' => $baseDir . '/app/controladores/ControladorInicio.php',
    'ControladorReportes' => $baseDir . '/app/controladores/ControladorReportes.php',
    'Dompdf\\Cpdf' => $vendorDir . '/dompdf/dompdf/lib/Cpdf.php',
    'HTML5_Data' => $vendorDir . '/dompdf/dompdf/lib/html5lib/Data.php',
    'HTML5_InputStream' => $vendorDir . '/dompdf/dompdf/lib/html5lib/InputStream.php',
    'HTML5_Parser' => $vendorDir . '/dompdf/dompdf/lib/html5lib/Parser.php',
    'HTML5_Tokenizer' => $vendorDir . '/dompdf/dompdf/lib/html5lib/Tokenizer.php',
    'HTML5_TreeBuilder' => $vendorDir . '/dompdf/dompdf/lib/html5lib/TreeBuilder.php',
    'Modelo' => $baseDir . '/app/libs/Modelo.php',
    'ModeloAsignacion' => $baseDir . '/app/modelos/ModeloAsignacion.php',
    'ModeloAvance' => $baseDir . '/app/modelos/ModeloAvance.php',
    'ModeloCliente' => $baseDir . '/app/modelos/ModeloCliente.php',
    'ModeloEmpleado' => $baseDir . '/app/modelos/ModeloEmpleado.php',
    'ModeloProyecto' => $baseDir . '/app/modelos/ModeloProyecto.php',
    'ModeloSolicitud' => $baseDir . '/app/modelos/ModeloSolicitud.php',
    'ModeloUsuario' => $baseDir . '/app/modelos/ModeloUsuario.php',
    'Seguridad' => $baseDir . '/app/helpers/Seguridad.php',
    'Sesion' => $baseDir . '/app/helpers/Sesion.php',
    'Validador' => $baseDir . '/app/helpers/Validador.php',
    'Vista' => $baseDir . '/app/libs/Vista.php',
);
